# https://bookdown.org/yihui/blogdown/

baseURL = "https://projectmayhem.netlify.app"
title = "Your title"
theme = "hugo-theme-m10c"
paginate = 5

[params]
  author = "Ali Osman ÖZTOP"
  description = "Finans ve R"
  [[params.social]]
    name = "github"
    url = "https://github.com/fabricandofitfaber"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
