---
title: dstack
author: fabricandofitfaber
date: '2020-09-27'
slug: dstack
categories:
  - data visualization
tags:
  - data visualization
  - graphs
---

## install packages and identifying dstack.ai account
```{r}
install.packages("dstack")

dstack::configure(user = "harry_tuttle", 
                  token = "ba018341-8d3e-4fc8-9f56-b30485b117a0", 
                  persist = "global")
```

## attach library and dataset
```{r}
library(ggplot2)
library(dstack)

df <- data.frame(x = c(2, 6, 9, 7), y = c(1, 4, 9, 16))
image <- ggplot(data = df, aes(x = x, y = y)) + geom_line()

push_frame("simple_man", image, "My second plot")
```


## make line_plot
```{r}
line_plot <- function(a) {
  
  x <- c(0:20)
  
  y <- sapply(x, function(x) { return(a * x) })
  
  df <- data.frame(x = x, y = y)
  
  plot <- ggplot(data = df, aes(x = x, y = y)) + 
    geom_line() + xlim(0, 20) + ylim(0, 20)
  return(plot)
  
}

coeff <- c(0.5, 1.0, 1.5, 2.0)
frame <- create_frame(stack = "line_plot")
for(c in coeff) {
  
  frame <- commit(frame, line_plot(c), 
                  paste0("Line plot with the coefficient of ", c), 
                  Coefficient = c)
}

push(frame)
```